// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscribeRespProto.proto

package netty.d_protobuf_02_netty.src.main.java.cn.proto;

public final class SubscribeRespProto {
  private SubscribeRespProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubscribeRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netty.SubscribeResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string subReqID = 1;</code>
     */
    String getSubReqID();
    /**
     * <code>string subReqID = 1;</code>
     */
    com.google.protobuf.ByteString
        getSubReqIDBytes();

    /**
     * <code>int32 reqCode = 2;</code>
     */
    int getReqCode();

    /**
     * <code>string subscribe = 3;</code>
     */
    String getSubscribe();
    /**
     * <code>string subscribe = 3;</code>
     */
    com.google.protobuf.ByteString
        getSubscribeBytes();
  }
  /**
   * Protobuf type {@code netty.SubscribeResp}
   */
  public  static final class SubscribeResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:netty.SubscribeResp)
      SubscribeRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubscribeResp.newBuilder() to construct.
    private SubscribeResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubscribeResp() {
      subReqID_ = "";
      subscribe_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new SubscribeResp();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SubscribeResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              subReqID_ = s;
              break;
            }
            case 16: {

              reqCode_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              subscribe_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.internal_static_netty_SubscribeResp_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.internal_static_netty_SubscribeResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp.class, netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp.Builder.class);
    }

    public static final int SUBREQID_FIELD_NUMBER = 1;
    private volatile Object subReqID_;
    /**
     * <code>string subReqID = 1;</code>
     */
    public String getSubReqID() {
      Object ref = subReqID_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        subReqID_ = s;
        return s;
      }
    }
    /**
     * <code>string subReqID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSubReqIDBytes() {
      Object ref = subReqID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        subReqID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQCODE_FIELD_NUMBER = 2;
    private int reqCode_;
    /**
     * <code>int32 reqCode = 2;</code>
     */
    public int getReqCode() {
      return reqCode_;
    }

    public static final int SUBSCRIBE_FIELD_NUMBER = 3;
    private volatile Object subscribe_;
    /**
     * <code>string subscribe = 3;</code>
     */
    public String getSubscribe() {
      Object ref = subscribe_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        subscribe_ = s;
        return s;
      }
    }
    /**
     * <code>string subscribe = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSubscribeBytes() {
      Object ref = subscribe_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        subscribe_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSubReqIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, subReqID_);
      }
      if (reqCode_ != 0) {
        output.writeInt32(2, reqCode_);
      }
      if (!getSubscribeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, subscribe_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSubReqIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, subReqID_);
      }
      if (reqCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, reqCode_);
      }
      if (!getSubscribeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, subscribe_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp)) {
        return super.equals(obj);
      }
      netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp other = (netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp) obj;

      if (!getSubReqID()
          .equals(other.getSubReqID())) return false;
      if (getReqCode()
          != other.getReqCode()) return false;
      if (!getSubscribe()
          .equals(other.getSubscribe())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUBREQID_FIELD_NUMBER;
      hash = (53 * hash) + getSubReqID().hashCode();
      hash = (37 * hash) + REQCODE_FIELD_NUMBER;
      hash = (53 * hash) + getReqCode();
      hash = (37 * hash) + SUBSCRIBE_FIELD_NUMBER;
      hash = (53 * hash) + getSubscribe().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.SubscribeResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netty.SubscribeResp)
        netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.internal_static_netty_SubscribeResp_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.internal_static_netty_SubscribeResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp.class, netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp.Builder.class);
      }

      // Construct using com.netty.d_protobuf_self.src.main.java.netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        subReqID_ = "";

        reqCode_ = 0;

        subscribe_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.internal_static_netty_SubscribeResp_descriptor;
      }

      @Override
      public netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp getDefaultInstanceForType() {
        return netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp.getDefaultInstance();
      }

      @Override
      public netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp build() {
        netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp buildPartial() {
        netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp result = new netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp(this);
        result.subReqID_ = subReqID_;
        result.reqCode_ = reqCode_;
        result.subscribe_ = subscribe_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp) {
          return mergeFrom((netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp other) {
        if (other == netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp.getDefaultInstance()) return this;
        if (!other.getSubReqID().isEmpty()) {
          subReqID_ = other.subReqID_;
          onChanged();
        }
        if (other.getReqCode() != 0) {
          setReqCode(other.getReqCode());
        }
        if (!other.getSubscribe().isEmpty()) {
          subscribe_ = other.subscribe_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object subReqID_ = "";
      /**
       * <code>string subReqID = 1;</code>
       */
      public String getSubReqID() {
        Object ref = subReqID_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          subReqID_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string subReqID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSubReqIDBytes() {
        Object ref = subReqID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          subReqID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string subReqID = 1;</code>
       */
      public Builder setSubReqID(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subReqID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string subReqID = 1;</code>
       */
      public Builder clearSubReqID() {
        
        subReqID_ = getDefaultInstance().getSubReqID();
        onChanged();
        return this;
      }
      /**
       * <code>string subReqID = 1;</code>
       */
      public Builder setSubReqIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subReqID_ = value;
        onChanged();
        return this;
      }

      private int reqCode_ ;
      /**
       * <code>int32 reqCode = 2;</code>
       */
      public int getReqCode() {
        return reqCode_;
      }
      /**
       * <code>int32 reqCode = 2;</code>
       */
      public Builder setReqCode(int value) {
        
        reqCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 reqCode = 2;</code>
       */
      public Builder clearReqCode() {
        
        reqCode_ = 0;
        onChanged();
        return this;
      }

      private Object subscribe_ = "";
      /**
       * <code>string subscribe = 3;</code>
       */
      public String getSubscribe() {
        Object ref = subscribe_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          subscribe_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string subscribe = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSubscribeBytes() {
        Object ref = subscribe_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          subscribe_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string subscribe = 3;</code>
       */
      public Builder setSubscribe(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subscribe_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string subscribe = 3;</code>
       */
      public Builder clearSubscribe() {
        
        subscribe_ = getDefaultInstance().getSubscribe();
        onChanged();
        return this;
      }
      /**
       * <code>string subscribe = 3;</code>
       */
      public Builder setSubscribeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subscribe_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:netty.SubscribeResp)
    }

    // @@protoc_insertion_point(class_scope:netty.SubscribeResp)
    private static final netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp();
    }

    public static netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubscribeResp>
        PARSER = new com.google.protobuf.AbstractParser<SubscribeResp>() {
      @Override
      public SubscribeResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubscribeResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubscribeResp> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SubscribeResp> getParserForType() {
      return PARSER;
    }

    @Override
    public netty.d_protobuf_02_netty.src.main.java.cn.proto.SubscribeRespProto.SubscribeResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_SubscribeResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netty_SubscribeResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030SubscribeRespProto.proto\022\005netty\"E\n\rSub" +
      "scribeResp\022\020\n\010subReqID\030\001 \001(\t\022\017\n\007reqCode\030" +
      "\002 \001(\005\022\021\n\tsubscribe\030\003 \001(\tB5\n\037com.netty.d_" +
      "protobuf_self.protoB\022SubscribeRespProtob" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_netty_SubscribeResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netty_SubscribeResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netty_SubscribeResp_descriptor,
        new String[] { "SubReqID", "ReqCode", "Subscribe", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
